version: "3.8"
services:
  sourcingdb:
    image: mongo
  orderingdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:3.13.4-management
  product.api:
    image: product_api_image
    build:
     context: .
     dockerfile: ESourcing.Products/Dockerfile
  sourcing.api:
    image: sourcing_api_image
    build:
     context: .
     dockerfile: ESourcing.Sourcing/Dockerfile
  order.api:
    image: order_api_image
    build:
      context: .
      dockerfile: ESourcing.Order/Dockerfile
volumes:
  sourcingdb_volume:
  orderingdb_volume: