version: "3.8"
services:
  sourcingdb:
    image: mongo
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  rabbitmq:
    image: rabbitmq:3.13.4-management
  product.api:
    image: product_api_image
    build:
     context: .
     dockerfile: ESourcing.Products/Dockerfile
  sourcing.api:
    image: sourcing_api_image
    build:
     context: .
     dockerfile: ESourcing.Sourcing/Dockerfile
volumes:
  sourcingdb_volume:
  orderdb_volume: