version: "3.8"
services:
  sourcingdb:
    image: mongo
  product.api:
    image: product_api_image
    build:
     context: .
     dockerfile: ESourcing.Products/Dockerfile
  sourcing.api:
    image: sourcing_api_image
    build:
     context: .
     dockerfile: ESourcing.Sourcing/Dockerfile
volumes:
  sourcingdb_volume: